### ISSUE TITLE
Typo in "homepage" value leads to a broken link, potentially hurting adoption

### ISSUE THREAD

**Issue by bobaekang** [alteredorange/astro-image#1]
I noticed a typo in the following line (missing "e" in the username): https://github.com/alteredorange/astro-infinity/blob/33453022e6eb6c48c2d24ac83e45eeb3d740cc06/packages/astro-infinity/package.json#L9

This can hurt your integration's adoption since [the Astro website's integration page](https://astro.build/integrations/) uses `homepage` value to create a link for each integration card, like the following: 

<img width="481" alt="image" src="https://user-images.githubusercontent.com/22449454/166255034-f8174ba8-3fc2-43f0-ad22-5d6d1a2e7beb.png">

See this comment from the Astro team for a recommended fix: https://github.com/withastro/astro.build/pull/109#issuecomment-1114962534

**Comment by alteredorange** [comment]
Oh maaaaaan, how did that happen? Not sure how I messed up a copy and paste :) thanks so much for the heads up @bobaekang!
